//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 05:48:28 PM IST 
//


package com.ericsson.am.xsd;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for httpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="httpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="socketTimeToLive" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="socketTimeout" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="connectionTimeout" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="idleConnectionsHandlerInterval" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "httpType")
public class HttpType {

    @XmlAttribute(name = "socketTimeToLive", required = true)
    protected BigInteger socketTimeToLive;
    @XmlAttribute(name = "socketTimeout", required = true)
    protected BigInteger socketTimeout;
    @XmlAttribute(name = "connectionTimeout", required = true)
    protected BigInteger connectionTimeout;
    @XmlAttribute(name = "idleConnectionsHandlerInterval", required = true)
    protected BigInteger idleConnectionsHandlerInterval;

    /**
     * Gets the value of the socketTimeToLive property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSocketTimeToLive() {
        return socketTimeToLive;
    }

    /**
     * Sets the value of the socketTimeToLive property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSocketTimeToLive(BigInteger value) {
        this.socketTimeToLive = value;
    }

    /**
     * Gets the value of the socketTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSocketTimeout() {
        return socketTimeout;
    }

    /**
     * Sets the value of the socketTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSocketTimeout(BigInteger value) {
        this.socketTimeout = value;
    }

    /**
     * Gets the value of the connectionTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getConnectionTimeout() {
        return connectionTimeout;
    }

    /**
     * Sets the value of the connectionTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setConnectionTimeout(BigInteger value) {
        this.connectionTimeout = value;
    }

    /**
     * Gets the value of the idleConnectionsHandlerInterval property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdleConnectionsHandlerInterval() {
        return idleConnectionsHandlerInterval;
    }

    /**
     * Sets the value of the idleConnectionsHandlerInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdleConnectionsHandlerInterval(BigInteger value) {
        this.idleConnectionsHandlerInterval = value;
    }

}
