//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 05:48:28 PM IST 
//


package com.ericsson.am.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="globalsettings" type="{http://www.ericsson.com/am/xsd}globalsettingsType"/>
 *         &lt;element name="security" type="{http://www.ericsson.com/am/xsd}securityType"/>
 *         &lt;element name="businesslogic" type="{http://www.ericsson.com/am/xsd}businesslogicType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="modules" type="{http://www.ericsson.com/am/xsd}modulesType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="defaultLanguage" type="{http://www.w3.org/2001/XMLSchema}string" default="en" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "globalsettings",
    "security",
    "businesslogic",
    "modules"
})
@XmlRootElement(name = "lwam")
public class Lwam {

    @XmlElement(required = true)
    protected GlobalsettingsType globalsettings;
    @XmlElement(required = true)
    protected SecurityType security;
    protected List<BusinesslogicType> businesslogic;
    @XmlElement(required = true)
    protected ModulesType modules;
    @XmlAttribute(name = "defaultLanguage")
    protected String defaultLanguage;

    /**
     * Gets the value of the globalsettings property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalsettingsType }
     *     
     */
    public GlobalsettingsType getGlobalsettings() {
        return globalsettings;
    }

    /**
     * Sets the value of the globalsettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalsettingsType }
     *     
     */
    public void setGlobalsettings(GlobalsettingsType value) {
        this.globalsettings = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityType }
     *     
     */
    public SecurityType getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityType }
     *     
     */
    public void setSecurity(SecurityType value) {
        this.security = value;
    }

    /**
     * Gets the value of the businesslogic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the businesslogic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBusinesslogic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BusinesslogicType }
     * 
     * 
     */
    public List<BusinesslogicType> getBusinesslogic() {
        if (businesslogic == null) {
            businesslogic = new ArrayList<BusinesslogicType>();
        }
        return this.businesslogic;
    }

    /**
     * Gets the value of the modules property.
     * 
     * @return
     *     possible object is
     *     {@link ModulesType }
     *     
     */
    public ModulesType getModules() {
        return modules;
    }

    /**
     * Sets the value of the modules property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModulesType }
     *     
     */
    public void setModules(ModulesType value) {
        this.modules = value;
    }

    /**
     * Gets the value of the defaultLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultLanguage() {
        if (defaultLanguage == null) {
            return "en";
        } else {
            return defaultLanguage;
        }
    }

    /**
     * Sets the value of the defaultLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultLanguage(String value) {
        this.defaultLanguage = value;
    }

}
