//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 05:48:28 PM IST 
//


package com.ericsson.am.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ericsson.am.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Smsmodule_QNAME = new QName("http://www.ericsson.com/am/xsd", "smsmodule");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ericsson.am.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Lwam }
     * 
     */
    public Lwam createLwam() {
        return new Lwam();
    }

    /**
     * Create an instance of {@link GlobalsettingsType }
     * 
     */
    public GlobalsettingsType createGlobalsettingsType() {
        return new GlobalsettingsType();
    }

    /**
     * Create an instance of {@link SecurityType }
     * 
     */
    public SecurityType createSecurityType() {
        return new SecurityType();
    }

    /**
     * Create an instance of {@link BusinesslogicType }
     * 
     */
    public BusinesslogicType createBusinesslogicType() {
        return new BusinesslogicType();
    }

    /**
     * Create an instance of {@link ModulesType }
     * 
     */
    public ModulesType createModulesType() {
        return new ModulesType();
    }

    /**
     * Create an instance of {@link SmsmoduleType }
     * 
     */
    public SmsmoduleType createSmsmoduleType() {
        return new SmsmoduleType();
    }

    /**
     * Create an instance of {@link PropertyListType }
     * 
     */
    public PropertyListType createPropertyListType() {
        return new PropertyListType();
    }

    /**
     * Create an instance of {@link PropertiesType }
     * 
     */
    public PropertiesType createPropertiesType() {
        return new PropertiesType();
    }

    /**
     * Create an instance of {@link ModuleType }
     * 
     */
    public ModuleType createModuleType() {
        return new ModuleType();
    }

    /**
     * Create an instance of {@link RemotesType }
     * 
     */
    public RemotesType createRemotesType() {
        return new RemotesType();
    }

    /**
     * Create an instance of {@link PropertyListsType }
     * 
     */
    public PropertyListsType createPropertyListsType() {
        return new PropertyListsType();
    }

    /**
     * Create an instance of {@link X509HostnameVerifierType }
     * 
     */
    public X509HostnameVerifierType createX509HostnameVerifierType() {
        return new X509HostnameVerifierType();
    }

    /**
     * Create an instance of {@link StatisticsType }
     * 
     */
    public StatisticsType createStatisticsType() {
        return new StatisticsType();
    }

    /**
     * Create an instance of {@link NotificationType }
     * 
     */
    public NotificationType createNotificationType() {
        return new NotificationType();
    }

    /**
     * Create an instance of {@link MapType }
     * 
     */
    public MapType createMapType() {
        return new MapType();
    }

    /**
     * Create an instance of {@link NotificationsType }
     * 
     */
    public NotificationsType createNotificationsType() {
        return new NotificationsType();
    }

    /**
     * Create an instance of {@link KeystoreType }
     * 
     */
    public KeystoreType createKeystoreType() {
        return new KeystoreType();
    }

    /**
     * Create an instance of {@link RemoteType }
     * 
     */
    public RemoteType createRemoteType() {
        return new RemoteType();
    }

    /**
     * Create an instance of {@link SessionType }
     * 
     */
    public SessionType createSessionType() {
        return new SessionType();
    }

    /**
     * Create an instance of {@link OperationsType }
     * 
     */
    public OperationsType createOperationsType() {
        return new OperationsType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link OperationType }
     * 
     */
    public OperationType createOperationType() {
        return new OperationType();
    }

    /**
     * Create an instance of {@link HttpType }
     * 
     */
    public HttpType createHttpType() {
        return new HttpType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SmsmoduleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ericsson.com/am/xsd", name = "smsmodule")
    public JAXBElement<SmsmoduleType> createSmsmodule(SmsmoduleType value) {
        return new JAXBElement<SmsmoduleType>(_Smsmodule_QNAME, SmsmoduleType.class, null, value);
    }

}
