//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 05:48:28 PM IST 
//


package com.ericsson.am.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for securityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="securityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="keystore" type="{http://www.ericsson.com/am/xsd}keystoreType"/>
 *         &lt;element name="X509HostnameVerifier" type="{http://www.ericsson.com/am/xsd}X509HostnameVerifierType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "securityType", propOrder = {
    "keystore",
    "x509HostnameVerifier"
})
public class SecurityType {

    @XmlElement(required = true)
    protected KeystoreType keystore;
    @XmlElement(name = "X509HostnameVerifier", required = true)
    protected X509HostnameVerifierType x509HostnameVerifier;

    /**
     * Gets the value of the keystore property.
     * 
     * @return
     *     possible object is
     *     {@link KeystoreType }
     *     
     */
    public KeystoreType getKeystore() {
        return keystore;
    }

    /**
     * Sets the value of the keystore property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeystoreType }
     *     
     */
    public void setKeystore(KeystoreType value) {
        this.keystore = value;
    }

    /**
     * Gets the value of the x509HostnameVerifier property.
     * 
     * @return
     *     possible object is
     *     {@link X509HostnameVerifierType }
     *     
     */
    public X509HostnameVerifierType getX509HostnameVerifier() {
        return x509HostnameVerifier;
    }

    /**
     * Sets the value of the x509HostnameVerifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link X509HostnameVerifierType }
     *     
     */
    public void setX509HostnameVerifier(X509HostnameVerifierType value) {
        this.x509HostnameVerifier = value;
    }

}
