//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 05:48:28 PM IST 
//


package com.ericsson.am.xsd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for X509HostnameVerifierValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="X509HostnameVerifierValueType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="STRICT_HOSTNAME_VERIFIER"/>
 *     &lt;enumeration value="BROWSER_COMPATIBLE_HOSTNAME_VERIFIER"/>
 *     &lt;enumeration value="ALLOW_ALL_HOSTNAME_VERIFIER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "X509HostnameVerifierValueType")
@XmlEnum
public enum X509HostnameVerifierValueType {

    STRICT_HOSTNAME_VERIFIER,
    BROWSER_COMPATIBLE_HOSTNAME_VERIFIER,
    ALLOW_ALL_HOSTNAME_VERIFIER;

    public String value() {
        return name();
    }

    public static X509HostnameVerifierValueType fromValue(String v) {
        return valueOf(v);
    }

}
