
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.server.atm;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-08-31T15:46:56.749+05:30
 * Generated source version: 2.7.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "ATM-atmcashoutService",
                      portName = "ATM-atmcashoutPort",
                      targetNamespace = "http://atm-atmcashout.em.emm.ericsson.com",
                      wsdlLocation = "wsdl/ATM-atmcashout.wsdl",
                      endpointInterface = "com.server.atm.ATMAtmcashoutPortType")
                      
public class ATMAtmcashoutPortTypeImpl implements ATMAtmcashoutPortType {

    private static final Logger LOG = Logger.getLogger(ATMAtmcashoutPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.server.atm.ATMAtmcashoutPortType#atmcashout(com.server.atm.Atmcashoutrequest  atmcashoutrequest )*
     */
    public com.server.atm.Atmcashoutresponse atmcashout(Atmcashoutrequest atmcashoutrequest) throws ErrorResponse_Exception    { 
    	System.out.println("Executing operation atmcashout");
        System.out.println(atmcashoutrequest);
        try {
            com.server.atm.Atmcashoutresponse _return = new Atmcashoutresponse();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ErrorResponse_Exception("errorResponse...");
    }

}
