package com.server.atm;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-08-31T15:46:56.810+05:30
 * Generated source version: 2.7.10
 * 
 */
@WebServiceClient(name = "ATM-atmcashoutService", 
                  wsdlLocation = "wsdl/ATM-atmcashout.wsdl",
                  targetNamespace = "http://atm-atmcashout.em.emm.ericsson.com") 
public class ATMAtmcashoutService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://atm-atmcashout.em.emm.ericsson.com", "ATM-atmcashoutService");
    public final static QName ATMAtmcashoutPort = new QName("http://atm-atmcashout.em.emm.ericsson.com", "ATM-atmcashoutPort");
    static {
        URL url = ATMAtmcashoutService.class.getResource("wsdl/ATM-atmcashout.wsdl");
        if (url == null) {
            url = ATMAtmcashoutService.class.getClassLoader().getResource("wsdl/ATM-atmcashout.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(ATMAtmcashoutService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "wsdl/ATM-atmcashout.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ATMAtmcashoutService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ATMAtmcashoutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ATMAtmcashoutService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ATMAtmcashoutService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ATMAtmcashoutService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ATMAtmcashoutService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ATMAtmcashoutPortType
     */
    @WebEndpoint(name = "ATM-atmcashoutPort")
    public ATMAtmcashoutPortType getATMAtmcashoutPort() {
        return super.getPort(ATMAtmcashoutPort, ATMAtmcashoutPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ATMAtmcashoutPortType
     */
    @WebEndpoint(name = "ATM-atmcashoutPort")
    public ATMAtmcashoutPortType getATMAtmcashoutPort(WebServiceFeature... features) {
        return super.getPort(ATMAtmcashoutPort, ATMAtmcashoutPortType.class, features);
    }

}
