package com.client.atm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-08-31T15:31:45.841+05:30
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://atm-atmcashout.em.emm.ericsson.com", name = "ATM-atmcashoutPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ATMAtmcashoutPortType {

    @WebResult(name = "atmcashoutresponse", targetNamespace = "http://atm-atmcashout.em.emm.ericsson.com", partName = "atmcashoutresponse")
    @WebMethod
    public Atmcashoutresponse atmcashout(
        @WebParam(partName = "atmcashoutrequest", name = "atmcashoutrequest", targetNamespace = "http://atm-atmcashout.em.emm.ericsson.com")
        Atmcashoutrequest atmcashoutrequest
    ) throws ErrorResponse_Exception;
}
