
package com.client.atm;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-08-31T15:31:45.785+05:30
 * Generated source version: 2.7.10
 */

@WebFault(name = "errorResponse", targetNamespace = "http://atm-atmcashout.em.emm.ericsson.com")
public class ErrorResponse_Exception extends Exception {
    
    private com.client.atm.ErrorResponse errorResponse;

    public ErrorResponse_Exception() {
        super();
    }
    
    public ErrorResponse_Exception(String message) {
        super(message);
    }
    
    public ErrorResponse_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ErrorResponse_Exception(String message, com.client.atm.ErrorResponse errorResponse) {
        super(message);
        this.errorResponse = errorResponse;
    }

    public ErrorResponse_Exception(String message, com.client.atm.ErrorResponse errorResponse, Throwable cause) {
        super(message, cause);
        this.errorResponse = errorResponse;
    }

    public com.client.atm.ErrorResponse getFaultInfo() {
        return this.errorResponse;
    }
}
